### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by c244a0** [c244a0/furima-38196#22]
URL: https://furima-38196.herokuapp.com/
Basic認証
ID:orwell
password:1984
出品者
email:a@a
password:aaaaaa1
購入者
email:b@b
password:aaaaaa1

**Comment by motomuun** [comment]
@c244a0 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x] **ページ下部の「もどる」ボタンを押すと、編集途中の情報は破棄され、商品詳細表示ページに遷移すること**
商品詳細ページでなく、トップページに遷移してしまいます。

- [x] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
URLを直接入力することで、自身が出品していない商品の編集ページにも遷移出来てしまいます。

**商品削除機能の確認**

- [x] **ログイン状態の場合にのみ、自身が出品した商品情報を削除できること**
削除ボタンを押しても削除が完了しません。

**商品購入機能の確認**

- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
必須項目を全て入力しても、下記が表示され購入することが出来ません。
<img width="1438" alt="スクリーンショット 2022-07-25 9 31 08" src="https://user-images.githubusercontent.com/65059944/180672782-eb7182fa-f18a-42c4-9647-f25bc8a699d5.png">

**S3**

- [ ] **本番環境で投稿した商品画像が、S3に保存されること**
画像がS3に保存されておりません。

※売却済み商品に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@c244a0 さん、 再度のご提出ありがとうございます‼︎
動作の確認をしたところ、修正出来ていない箇所と、
動作確認ができなかった売却済み商品に関して修正していただきたい箇所がございました。
改めて以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x]  **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**

```
[例：ユーザーAでログインして、商品を出品する。その時商品の編集ページURLをコピーしておく。
次に別のユーザーBでログインして、先ほどコピーしたURLを貼り付ける。この時、トップページに遷移すること。]
```
現状では、URLを直接入力することで、自身が出品していない商品の編集ページにも遷移出来てしまいます。

- [x] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
 ```
[例：ユーザーAでログインして、商品を出品する。その時商品の編集ページURLをコピーしておく。
ユーザーBで商品を購入した後、もう一度ユーザーAでログインし、先程コピーしたURLを貼り付ける。
この時、トップページに遷移すること]
```
現状では、URLを直接入力することで、自身が出品した売却済み商品の編集ページにも遷移出来てしまいます。

**S3**

- [ ]  **本番環境で投稿した商品画像が、S3に保存されること**
画像がS3に保存されておりません。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@c244a0 さん、再度のご提出ありがとうございます‼︎
動作の確認をしたところ、以下二点の修正が出来ておりませんでした。
改めて以下のご確認をお願いします！

[修正依頼箇所]


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@c244a0 さん、再度のご提出ありがとうございます‼︎
動作の確認をしたところ、以下二点の修正が出来ておりませんでした。
改めて以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x]  **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
売却済みの商品は、出品者であっても編集ページに遷移出来ないように修正をお願いします。
```
確認方法：ユーザーAでログインして、商品を出品する。その時商品の編集ページURLをコピーしておく。
ユーザーBで商品を購入した後、もう一度ユーザーAでログインし、先程コピーしたURLを貼り付ける。
この時、トップページに遷移することが正しい挙動。
```
```
正しい挙動：自分が出品した売却済み商品の商品情報編集ページURLを直接入力すると、トップページに遷移する
現在の挙動：自分が出品した売却済み商品の商品情報編集ページURLを直接入力すると、編集ページに遷移する
```

**S3**

- [ ]  **本番環境で投稿した商品画像が、S3に保存されること**
画像がS3に保存されておりません。
```
【確認方法】
① 出品した商品画像を右(2本指)クリック
② メニューの中から「新しいタブで画像を開く」を選択
③ 表示されるURLの中に「s3.amazonaws」というワードが含まれていることを確認
```


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@c244a0 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7680

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/65059944/180707796-5c178232-3c89-4d87-8cb1-988cde58656b.png)
